Repository woowa-techcamp-2021/store-10, pull requests merged in 2021-08, with the labels that each got.

#3 chore : 서버 기본 세팅
  server/.env.sample
  server/nodemon.json
  server/package-lock.json
  server/package.json
  server/src/api/middlewares/.keep
  server/src/api/routes/index.ts
  server/src/api/routes/user.ts
  server/src/app.ts
  server/src/config/index.ts
  server/src/controllers/user.ts
  server/src/loaders/express.ts
  server/src/loaders/index.ts
  server/src/models/.keep
  server/src/repositories/.keep
  server/src/services/.keep
  server/src/types/.keep
  server/tsconfig.json
Labels: Back, chore

#4 chore : 프론트엔드 기본 세팅
  .eslintrc
  .gitignore
  client/.babelrc
  client/images.d.ts
  client/package-lock.json
  client/package.json
  client/src/Components/Header/index.tsx
  client/src/assets/index.ts
  client/src/assets/stationery.png
  client/src/assets/stationery.svg
  client/src/index.html
  client/src/index.tsx
  client/src/layouts/App/index.tsx
  client/src/styles/globalStyle.ts
  client/tsconfig.json
  client/webpack.config.js
Labels: Front, chore

#8 chore: router 적용 및 폴더 구조 기본 세팅
  client/jest.config.js
  client/package-lock.json
  client/package.json
  client/src/Components/Banner/Banner.test.tsx
  client/src/Components/Banner/Banner.tsx
  client/src/Components/Banner/index.tsx
  client/src/Components/Banner/styles.ts
  client/src/Components/Footer/Footer.test.tsx
  client/src/Components/Footer/Footer.tsx
  client/src/Components/Footer/index.tsx
  client/src/Components/Footer/styles.ts
  client/src/Components/Header/Header.tsx
  client/src/Components/Header/index.test.tsx
  client/src/Components/Header/index.tsx
  client/src/Components/Header/styles.ts
  client/src/core/router.tsx
  client/src/index.tsx
  client/src/layouts/App/App.test.tsx
  client/src/layouts/App/App.tsx
  client/src/layouts/App/index.tsx
  client/src/layouts/App/styles.ts
  client/src/pages/Detail/Detail.test.tsx
  client/src/pages/Detail/Detail.tsx
  client/src/pages/Detail/index.tsx
  client/src/pages/Detail/styles.ts
  client/src/pages/Main/Main.test.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/Main/styles.ts
  client/src/server/server.ts
  client/src/setupTest.js
Labels: Front, chore

#15 chore: router 기능 마무리 구현
  client/src/Components/Banner/Banner.tsx
  client/src/Components/Banner/styles.ts
  client/src/Components/Footer/Footer.tsx
  client/src/Components/Footer/styles.ts
  client/src/Components/Header/Header.tsx
  client/src/Components/Header/styles.ts
  client/src/core/router.tsx
  client/src/layouts/App/App.tsx
  client/src/pages/Detail/Detail.tsx
  client/src/pages/Detail/styles.ts
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/styles.ts
  client/src/pages/NavLinks/NavLinks.test.tsx
  client/src/pages/NavLinks/NavLinks.tsx
  client/src/pages/NavLinks/index.tsx
  client/src/pages/NavLinks/styles.ts
Labels: enhancement, Front, chore

#16 [#13] 인풋 컴포넌트 추가 및 스토리북 세팅
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/Components/Banner/Banner.stories.tsx
  client/src/Components/Banner/Banner.test.tsx
  client/src/Components/Footer/Footer.stories.tsx
  client/src/Components/Footer/Footer.test.tsx
  client/src/Components/Header/Header.stories.tsx
  client/src/Components/Header/index.test.tsx
  client/src/Components/Input/Input.stories.tsx
  client/src/Components/Input/Input.tsx
  client/src/Components/Input/index.tsx
  client/src/Components/Input/style.ts
  client/src/layouts/App/App.test.tsx
  client/src/pages/Detail/Detail.test.tsx
  client/src/pages/Main/Main.test.tsx
  client/src/pages/NavLinks/NavLinks.test.tsx
  client/webpack.config.js
Labels: Front, chore

#18 [#17] feat: 스토리북 애드온 추가, 피그마 추가, chromatic 자동배포 테스트
  .github/workflows/chromatic.yml
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/Components/Figma/Figma.stories.tsx
  client/src/Components/Figma/Figma.tsx
  client/src/Components/Figma/index.tsx
  client/src/Components/Input/style.ts
Labels: Front, chore, deploy

#20 [style] globalStyle 및 theme 적용 & 스토리북 ThemeProvider 기본 설정
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/Components/Banner/Banner.tsx
  client/src/Components/Banner/styles.ts
  client/src/core/router.tsx
  client/src/index.html
  client/src/index.tsx
  client/src/layouts/App/App.tsx
  client/src/styles/globalStyle.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: enhancement, Front

#19 [#17] wip: 자동 배포 및 pr ui test 테스트
  .github/workflows/chromatic.yml
  client/package.json
Labels: Front, chore, deploy

#33 [#12] feat : 헤더 컴포넌트 추가
  client/src/assets/svgs/close.svg
  client/src/assets/svgs/heart.svg
  client/src/assets/svgs/index.ts
  client/src/assets/svgs/like.svg
  client/src/assets/svgs/menu.svg
  client/src/assets/svgs/search.svg
  client/src/assets/svgs/shoppingCart.svg
  client/src/assets/svgs/stationery.svg
  client/src/assets/svgs/user.svg
  client/src/components/Card/Card.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Header/Search/Search.tsx
  client/src/components/Header/Search/index.tsx
  client/src/components/Header/Search/styles.ts
  client/src/components/Header/Sidebar/Sidebar.tsx
  client/src/components/Header/Sidebar/index.tsx
  client/src/components/Header/Sidebar/styles.ts
  client/src/components/Header/styles.ts
  client/src/dummies/categorys.ts
  client/src/hooks/useRecentSearch.tsx
  client/src/layouts/App/styles.ts
  client/src/pages/Detail/Detail.tsx
  client/src/styles/globalStyle.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: Front

#34 [#28, #29, #30] 타이틀 컴포넌트, 버튼 컴포넌트, 로그인 페이지 추가
  .github/workflows/chromatic.yml
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/assets/github.svg
  client/src/components/Button/Button.stories.tsx
  client/src/components/Button/Button.tsx
  client/src/components/Button/index.tsx
  client/src/components/Button/styles.ts
  client/src/components/Footer/styles.ts
  client/src/components/Input/style.ts
  client/src/components/Title/Title.stories.tsx
  client/src/components/Title/Title.tsx
  client/src/components/Title/index.tsx
  client/src/components/Title/style.ts
  client/src/layouts/App/App.tsx
  client/src/layouts/App/styles.ts
  client/src/pages/Login/Login.stories.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Login/index.tsx
  client/src/pages/Login/styles.ts
Labels: enhancement, Front, chore

#38 [#37] auto assign 워크플로우 추가
  .github/auto_assign.yml
Labels: chore

#35 [feat] Banner 컴포넌트 Carousel 적용
  .github/PULL_REQUEST_TEMPLATE.md
  client/package-lock.json
  client/package.json
  client/src/components/Banner/Banner.tsx
  client/src/components/Banner/styles.ts
  client/src/components/Card/styles.ts
  client/src/components/CardWrapper/styles.ts
  client/src/components/Header/Header.tsx
  client/src/layouts/App/App.tsx
  client/src/layouts/App/styles.ts
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/styles.ts
  client/src/styles/globalStyle.ts
Labels: enhancement, Front

#43 Footer 컴포넌트 작성
  client/src/assets/svgs/email.svg
  client/src/assets/svgs/fax.svg
  client/src/assets/svgs/index.ts
  client/src/assets/svgs/instagram.svg
  client/src/components/Card/styles.ts
  client/src/components/Footer/Footer.tsx
  client/src/components/Footer/styles.ts
  client/src/components/Header/Header.tsx
  client/src/components/Header/styles.ts
  client/src/layouts/App/App.tsx
  client/src/layouts/App/styles.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: enhancement, Front

#45 체크 박스 추가
  client/src/assets/svgs/check.svg
  client/src/assets/svgs/index.ts
  client/src/assets/svgs/minus.svg
  client/src/assets/svgs/plus.svg
  client/src/components/Checkbox/Checkbox.stories.tsx
  client/src/components/Checkbox/Checkbox.tsx
  client/src/components/Checkbox/index.tsx
  client/src/components/Checkbox/styles.ts
Labels: Front

#46 장바구니 페이지 추가
  client/src/components/Checkbox/Checkbox.tsx
  client/src/components/Header/Header.tsx
  client/src/components/ShoppingCart/ShopingCartItem/ShopingCartItem.tsx
  client/src/components/ShoppingCart/ShopingCartItem/index.tsx
  client/src/components/ShoppingCart/ShopingCartItem/styles.ts
  client/src/components/ShoppingCart/ShoppingCartList/ShoppingCart.stories.tsx
  client/src/components/ShoppingCart/ShoppingCartList/ShoppingCartList.tsx
  client/src/components/ShoppingCart/ShoppingCartList/index.tsx
  client/src/components/ShoppingCart/ShoppingCartList/styles.ts
  client/src/components/ShoppingCart/ShoppingCartSummary/ShoppingCart.stories.tsx
  client/src/components/ShoppingCart/ShoppingCartSummary/ShoppingCartSummary.tsx
  client/src/components/ShoppingCart/ShoppingCartSummary/index.tsx
  client/src/components/ShoppingCart/ShoppingCartSummary/styles.ts
  client/src/dummies/shoppingCart.ts
  client/src/helper/index.ts
  client/src/layouts/App/App.tsx
  client/src/pages/ShoppingCart/ShoppingCart.stories.tsx
  client/src/pages/ShoppingCart/ShoppingCart.tsx
  client/src/pages/ShoppingCart/index.tsx
  client/src/pages/ShoppingCart/styles.ts
  client/src/styles/globalStyle.ts
  client/src/types/index.ts
Labels: Front

#47 유효하지 않은 URL 입력 시 보여지는 화면 제작
  client/.storybook/preview.js
  client/package-lock.json
  client/src/components/Footer/styles.ts
  client/src/components/NotFound/NotFound.stories.tsx
  client/src/components/NotFound/NotFound.tsx
  client/src/components/NotFound/index.tsx
  client/src/components/NotFound/styles.ts
  client/src/core/Router.tsx
  client/src/layouts/App/App.tsx
  client/src/styles/globalStyle.ts
Labels: enhancement, Front

#57 서버 자동배포 코드 추가 및 db env 설정
  .github/workflows/server_deploy.yml
  server/.env.sample
  server/ecosystem.config.js
  server/ormconfig.json
  server/ormconfig.ts
  server/package-lock.json
  server/package.json
  server/src/api/routes/index.ts
  server/src/config/index.ts
Labels: Back, chore, deploy

#59 프론트엔드 자동 배포 추가
  .github/workflows/chromatic.yml
  .github/workflows/client_deploy.yml
  appspec.yml
Labels: Front, deploy

#58 모달 컴포넌트 기본 레이아웃 및 예시 커스텀 모달 작성
  client/.storybook/preview-head.html
  client/src/components/Modal/ModalLayout/ModalLayout.tsx
  client/src/components/Modal/ModalLayout/index.tsx
  client/src/components/Modal/ModalLayout/styles.ts
  client/src/components/Modal/PolicyModal.stories.tsx
  client/src/components/Modal/PolicyModal.tsx
  client/src/components/Modal/Portal/Portal.tsx
  client/src/components/Modal/Portal/index.tsx
  client/src/components/Modal/styles.ts
  client/src/index.html
  client/src/layouts/App/styles.ts
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/styles.ts
Labels: enhancement, Front

#60 Feature/page/mypage
  client/src/components/MyPage/MyPageAside/MyPageAside.stories.tsx
  client/src/components/MyPage/MyPageAside/MyPageAside.tsx
  client/src/components/MyPage/MyPageAside/index.tsx
  client/src/components/MyPage/MyPageAside/styles.ts
  client/src/layouts/App/App.tsx
  client/src/pages/mypage/MyPage.stories.tsx
  client/src/pages/mypage/MyPage.tsx
  client/src/pages/mypage/index.tsx
  client/src/pages/mypage/styles.ts
Labels: Front

#65 백엔드 추가 작업 (회원가입, 로그인, jwt)
  server/.env.sample
  server/ormconfig.ts
  server/package-lock.json
  server/package.json
  server/src/api/middlewares/.keep
  server/src/api/middlewares/auth.middlewares.ts
  server/src/api/routes/auth.router.ts
  server/src/api/routes/index.ts
  server/src/api/routes/user.router.ts
  server/src/api/routes/user.ts
  server/src/app.ts
  server/src/config/index.ts
  server/src/controllers/auth.controller.ts
  server/src/controllers/user.controller.ts
  server/src/controllers/user.ts
  server/src/entities/address.entity.ts
  server/src/entities/base.entity.ts
  server/src/entities/bookmark.entity.ts
  server/src/entities/cart.entity.ts
  server/src/entities/mainCategory.entity.ts
  server/src/entities/notice.entity.ts
  server/src/entities/prodectImage.entity.ts
  server/src/entities/product.entity.ts
  server/src/entities/purchase.entity.ts
  server/src/entities/question.entity.ts
  server/src/entities/questionImage.entity.ts
  server/src/entities/review.entity.ts
  server/src/entities/reviewImage.entity.ts
  server/src/entities/subCategory.entity.ts
  server/src/entities/user.entity.ts
  server/src/repositories/.keep
  server/src/repositories/oauth/git.oauth.ts
  server/src/repositories/user.repository.ts
  server/src/services/.keep
  server/src/services/auth.service.ts
  server/src/services/jwt.service.ts
  server/src/services/user.service.ts
  server/src/types/.keep
  server/src/types/express.d.ts
  server/src/utils/queryString.ts
  server/src/utils/wrapAsync.ts
Labels: Back, chore

#69 bcrypt -> bcrypt-nodejs
  server/package-lock.json
  server/package.json
  server/src/entities/user.entity.ts
  server/src/services/auth.service.ts
Labels: bug, deploy

#71 탭 공통 컴포넌트 작성
  client/src/components/Modal/index.tsx
  client/src/components/Tab/TabExample.stories.tsx
  client/src/components/Tab/TabExample.tsx
  client/src/components/Tab/TabExample2.tsx
  client/src/components/Tab/TabUI/Tab.tsx
  client/src/components/Tab/TabUI/TabContext.tsx
  client/src/components/Tab/TabUI/TabPanel.tsx
  client/src/components/Tab/TabUI/Tabs.tsx
  client/src/components/Tab/TabUI/index.tsx
  client/src/components/Tab/TabUI/styles.ts
  client/src/components/Tab/index.tsx
  client/src/pages/Detail/Detail.tsx
  client/src/pages/Main/Main.tsx
Labels: enhancement, Front

#78 회원가입 선택 페이지, 약관 동의 페이지, 회원가입 페이지 추가 및 인풋 컴포넌트 타입 추가
  client/package-lock.json
  client/src/assets/svgs/github.svg
  client/src/assets/svgs/index.ts
  client/src/components/Button/Button.stories.tsx
  client/src/components/Button/Button.tsx
  client/src/components/Button/styles.ts
  client/src/components/Input/Input.stories.tsx
  client/src/components/Input/Input.tsx
  client/src/components/Input/style.ts
  client/src/components/Title/style.ts
  client/src/layouts/App/App.tsx
  client/src/pages/Approval/Approval.stories.tsx
  client/src/pages/Approval/Approval.tsx
  client/src/pages/Approval/index.tsx
  client/src/pages/Approval/styles.ts
  client/src/pages/Login/Login.tsx
  client/src/pages/Login/styles.ts
  client/src/pages/SelectAuth/SelectAuth.stories.tsx
  client/src/pages/SelectAuth/SelectAuth.tsx
  client/src/pages/SelectAuth/index.tsx
  client/src/pages/SelectAuth/styles.ts
  client/src/pages/SignUp/SignUp.stories.tsx
  client/src/pages/SignUp/SignUp.tsx
  client/src/pages/SignUp/index.tsx
  client/src/pages/SignUp/styles.ts
  client/src/styles/global.scss
  client/src/utils/constant/approval.ts
  client/src/utils/constant/common.ts
Labels: enhancement, Front

#79 모달 관련 백그라운드 스크롤 설정 및 커스텀 훅 적용
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Modal/Portal/Portal.tsx
  client/src/hooks/useModal.tsx
  client/src/layouts/App/App.tsx
  client/src/pages/Main/Main.tsx
Labels: enhancement, Front, refactor

#80 상품 상세 페이지 매우 기본적인 마크업 진행
  client/src/assets/svgs/alert.svg
  client/src/assets/svgs/index.ts
  client/src/components/Card/Card.tsx
  client/src/components/Input/Input.stories.tsx
  client/src/components/Input/NumberInput.tsx
  client/src/components/Input/index.tsx
  client/src/components/Input/style.ts
  client/src/components/Modal/PolicyModal.stories.tsx
  client/src/components/Modal/PolicyModal.tsx
  client/src/components/Modal/ReviewModal.stories.tsx
  client/src/components/Modal/ReviewModal.tsx
  client/src/components/Modal/index.tsx
  client/src/components/ProductDetails/ProductDelivery/ProductDelivery.stories.tsx
  client/src/components/ProductDetails/ProductDelivery/ProductDelivery.tsx
  client/src/components/ProductDetails/ProductDelivery/index.tsx
  client/src/components/ProductDetails/ProductDescription/ProductDescription.stories.tsx
  client/src/components/ProductDetails/ProductDescription/ProductDescription.tsx
  client/src/components/ProductDetails/ProductDescription/index.tsx
  client/src/components/ProductDetails/ProductExchange.tsx/ProductExchange.stories.tsx
  client/src/components/ProductDetails/ProductExchange.tsx/ProductExchange.tsx
  client/src/components/ProductDetails/ProductExchange.tsx/index.tsx
  client/src/components/ProductDetails/ProductInfo/ProductInfo.stories.tsx
  client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
  client/src/components/ProductDetails/ProductInfo/index.tsx
  client/src/components/ProductDetails/ProductRequest/ProductRequest.stories.tsx
  client/src/components/ProductDetails/ProductRequest/ProductRequest.tsx
  client/src/components/ProductDetails/ProductRequest/index.tsx
  client/src/components/ProductDetails/ProductReview/ProductReview.stories.tsx
  client/src/components/ProductDetails/ProductReview/ProductReview.tsx
  client/src/components/ProductDetails/ProductReview/index.tsx
  client/src/components/ProductDetails/styles.ts
  client/src/components/Rating/Rating.stories.tsx
  client/src/components/Rating/Rating.tsx
  client/src/components/Rating/index.tsx
  client/src/components/Rating/styles.ts
  client/src/components/RatingChart/RatingChart.stories.tsx
  client/src/components/RatingChart/RatingChart.tsx
  client/src/components/RatingChart/index.tsx
  client/src/components/RatingChart/styles.ts
  client/src/components/Tab/ProductDetailTab.tsx
  client/src/components/Tab/TabExample2.tsx
  client/src/components/Tab/TabUI/TabContext.tsx
  client/src/components/Tab/TabUI/Tabs.tsx
  client/src/components/Tab/TabUI/styles.ts
  client/src/components/Tab/index.tsx
  client/src/components/Table/Table.tsx
  client/src/components/Table/styles.ts
  client/src/core/Router.tsx
  client/src/hooks/useNumberInput.tsx
  client/src/pages/Detail/Detail.tsx
  client/src/pages/Detail/styles.ts
  client/src/pages/Login/Login.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/styles.ts
  client/src/pages/SignUp/SignUp.tsx
Labels: enhancement, Front, refactor

#93 Eslint 설정파일 클라/서버로 분리하여 적용
  client/.eslintrc
  client/package-lock.json
  client/package.json
  server/.eslintrc
  server/package-lock.json
  server/package.json
Labels: Front, Back, refactor

#84 Feature/component/addresses
  client/package-lock.json
  client/package.json
  client/src/components/Address/Address.stories.tsx
  client/src/components/Address/Address.tsx
  client/src/components/Address/index.tsx
  client/src/components/Address/styles.ts
  client/src/components/Modal/AddressModal/AddressModal.stories.tsx
  client/src/components/Modal/AddressModal/AddressModal.tsx
  client/src/components/Modal/AddressModal/index.tsx
  client/src/components/Modal/AddressModal/styles.ts
  client/src/components/MyPage/MyPageAside/MyPageAside.tsx
  client/src/components/Shared/Checkbox/Checkbox.tsx
  client/src/components/Shared/Input/Input.tsx
  client/src/components/Shared/Modal/ModalLayout/ModalLayout.tsx
  client/src/components/Shared/Modal/ModalLayout/styles.ts
  client/src/contstants/index.ts
  client/src/dummies/addresses.ts
  client/src/pages/mypage/MyPage.tsx
  client/src/pages/mypage/styles.ts
  client/src/types/index.ts
  server/src/entities/address.entity.ts
Labels: Front

#95 린트 에러 수정 및 안쓰이는 변수 삭제 및 훅스 규칙 따르기
  .gitignore
  client/.eslintrc
  client/package-lock.json
  client/src/components/Addresses/Addresses.stories.tsx
  client/src/components/Addresses/Addresses.tsx
  client/src/components/Addresses/index.tsx
  client/src/components/Addresses/styles.ts
  client/src/components/Card/Card.tsx
  client/src/components/CardWrapper/CardWrapper.stories.tsx
  client/src/components/Header/Search/Search.tsx
  client/src/components/Header/Sidebar/Sidebar.tsx
  client/src/components/Header/Sidebar/styles.ts
  client/src/components/MyPage/MyPageAside/MyPageAside.tsx
  client/src/components/ProductDetails/ProductExchange.tsx/ProductExchange.tsx
  client/src/components/Shared/Checkbox/Checkbox.tsx
  client/src/components/Shared/Input/NumberInput.tsx
  client/src/components/Shared/Modal/ModalLayout/ModalLayout.tsx
  client/src/components/Shared/Modal/ReviewModal.tsx
  client/src/components/Shared/Tab/TabUI/TabContext.tsx
  client/src/components/Shared/Tab/TabUI/TabPanel.tsx
  client/src/components/Shared/Tab/TabUI/Tabs.tsx
  client/src/components/Shared/Table/Table.tsx
  client/src/components/ShoppingCart/ShopingCartItem/ShopingCartItem.tsx
  client/src/components/ShoppingCart/ShoppingCartList/ShoppingCart.stories.tsx
  client/src/components/ShoppingCart/ShoppingCartList/ShoppingCartList.tsx
  client/src/core/Router.tsx
  client/src/hooks/useNumberInput.tsx
  client/src/pages/Main/Main.tsx
  client/src/styles/globalStyle.ts
  client/src/styles/styled.d.ts
  server/.eslintrc
  server/src/api/routes/index.ts
  server/src/entities/base.entity.ts
  server/src/entities/cart.entity.ts
  server/src/entities/review.entity.ts
  server/src/entities/reviewImage.entity.ts
  server/src/loaders/dataInit.ts
  server/src/loaders/express.ts
  server/src/types/express.d.ts
  server/src/utils/wrapAsync.ts
Labels: Front, Back, refactor

#96 상품 상세 페이지 기본 마크업 완료
  client/src/assets/svgs/exchange.svg
  client/src/assets/svgs/gift.svg
  client/src/assets/svgs/index.ts
  client/src/assets/svgs/package.svg
  client/src/assets/svgs/upload.svg
  client/src/components/Address/Address.tsx
  client/src/components/Addresses/Addresses.tsx
  client/src/components/Footer/styles.ts
  client/src/components/Header/Header.tsx
  client/src/components/Modal/AddressModal/index.tsx
  client/src/components/Modal/AddressModal/styles.ts
  client/src/components/ProductDetails/ProductRequest/ProductRequest.tsx
  client/src/components/Shared/Button/Button.tsx
  client/src/components/Shared/Button/styles.ts
  client/src/components/Shared/Input/Input.tsx
  client/src/components/Shared/Input/style.ts
  client/src/components/Shared/Modal/AddressModal.stories.tsx
  client/src/components/Shared/Modal/AddressModal.tsx
  client/src/components/Shared/Modal/ModalLayout/styles.ts
  client/src/components/Shared/Modal/RequestModal.stories.tsx
  client/src/components/Shared/Modal/RequestModal.tsx
  client/src/components/Shared/Modal/ReviewModal.stories.tsx
  client/src/components/Shared/Modal/ReviewModal.tsx
  client/src/components/Shared/Modal/index.tsx
  client/src/components/Shared/Modal/styles.ts
  client/src/styles/globalStyle.ts
Labels: enhancement, Front, refactor

#98 [#91] :bug: bug: addresses -> address
  client/src/contstants/index.ts
Labels: Front

#100 인풋 관련 컴포넌트 모듈화 진행
  client/src/components/Header/styles.ts
  client/src/components/Shared/Input/FileInput.tsx
  client/src/components/Shared/Input/Textarea.tsx
  client/src/components/Shared/Input/index.tsx
  client/src/components/Shared/Input/style.ts
  client/src/components/Shared/Modal/RequestModal.tsx
  client/src/components/Shared/Modal/ReviewModal.tsx
  client/src/components/Shared/Modal/styles.ts
  client/src/components/Shared/Tab/ProductDetailTab.stories.tsx
  client/src/components/Shared/Tab/ProductDetailTab.tsx
  client/src/components/Shared/Tab/TabExample.stories.tsx
  client/src/components/Shared/Tab/TabUI/styles.ts
  client/src/hooks/useFileInput.tsx
Labels: enhancement, Front, refactor

#107 상품 상세 내용 json 데이터 입력 & 실 테스트
  crawler/main.go
  server/src/api/routes/product.router.ts
  server/src/controllers/product.controller.ts
  server/src/entities/product.entity.ts
  server/src/repositories/product.repository.ts
  server/src/services/product.service.ts
Labels: Back

#108 인풋 컴포넌트 라벨 기능 및 에러 기능 추가
  client/.storybook/preview.js
  client/src/components/Header/Header.stories.tsx
  client/src/components/Shared/Input/Input.tsx
  client/src/components/Shared/Input/style.ts
  client/src/layouts/App/App.tsx
  client/src/pages/SignUp/SignUp.tsx
  client/src/pages/SignUp/styles.ts
  client/src/pages/mypage/MyPage.stories.tsx
  client/src/styles/global.scss
  client/src/utils/constant/validate/validation.ts
Labels: enhancement, Front

#109 별점 컴포넌트 setter/getter 분리
  client/src/components/ProductDetails/ProductReview/ProductReview.tsx
  client/src/components/Shared/Modal/ReviewModal.tsx
  client/src/components/Shared/Rating/RatingGetter.stories.tsx
  client/src/components/Shared/Rating/RatingGetter.tsx
  client/src/components/Shared/Rating/RatingSetter.stories.tsx
  client/src/components/Shared/Rating/RatingSetter.tsx
  client/src/components/Shared/Rating/index.tsx
  client/src/components/Shared/Rating/styles.ts
Labels: enhancement, Front, refactor

#113 주문 내역 페이지 마크업
  client/src/assets/2.png
  client/src/components/Addresses/Addresses.stories.tsx
  client/src/components/Addresses/Addresses.tsx
  client/src/components/Addresses/index.tsx
  client/src/components/Addresses/styles.ts
  client/src/components/MyPage/MyPageAside/MyPageAside.tsx
  client/src/components/MyPage/MyPageAside/styles.ts
  client/src/components/MyPage/OrderHistory/OrderHistory.stories.tsx
  client/src/components/MyPage/OrderHistory/OrderHistory.tsx
  client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.stories.tsx
  client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.tsx
  client/src/components/MyPage/OrderHistory/OrderItemList/index.ts
  client/src/components/MyPage/OrderHistory/OrderItemList/styles.ts
  client/src/components/MyPage/OrderHistory/index.ts
  client/src/components/MyPage/OrderHistory/styles.ts
  client/src/components/Shared/Chip/Chip.stories.tsx
  client/src/components/Shared/Chip/Chip.tsx
  client/src/components/Shared/Chip/index.tsx
  client/src/components/Shared/Chip/style.ts
  client/src/contstants/index.ts
  client/src/dummies/orderHistory.ts
  client/src/pages/mypage/MyPage.tsx
  client/src/pages/mypage/styles.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: Front

#119 공지사항 페이지 작성
  client/src/components/Footer/Footer.tsx
  client/src/components/Shared/Collapse/Collapse.tsx
  client/src/components/Shared/Collapse/styles.ts
  client/src/layouts/App/App.tsx
  client/src/pages/NavLinks/NavLinks.tsx
  client/src/pages/NavLinks/index.tsx
  client/src/pages/NavLinks/styles.ts
  client/src/pages/Notice/Notice.stories.tsx
  client/src/pages/Notice/Notice.tsx
  client/src/pages/Notice/index.tsx
  client/src/pages/Notice/styles.ts
  client/src/utils/constant/notices.ts
Labels: enhancement, Front, refactor

#122 회원가입 페이지 작업 및 라우터 경로 변경
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/components/Card/Card.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/Header.tsx
  client/src/components/ProductDetails/ProductDescription/ProductDescription.tsx
  client/src/components/Shared/Button/Button.tsx
  client/src/components/Shared/Button/styles.ts
  client/src/index.tsx
  client/src/layouts/App/App.tsx
  client/src/lib/Router.tsx
  client/src/lib/api/client.ts
  client/src/lib/api/user/getCurrentUser.ts
  client/src/pages/Approval/Approval.tsx
  client/src/pages/Approval/styles.ts
  client/src/pages/Detail/Detail.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/SelectAuth/SelectAuth.tsx
  client/src/types/index.ts
  server/src/api/middlewares/auth.middlewares.ts
  server/src/api/routes/auth.router.ts
  server/src/controllers/auth.controller.ts
  server/src/loaders/express.ts
Labels: enhancement, Front, Back, refactor

#126 오타 수정 및 카트/상품/상품 이미지 조인 로직 추가
  server/src/controllers/cart.controller.ts
  server/src/entities/product.entity.ts
  server/src/entities/productImage.entity.ts
  server/src/loaders/dataInit.ts
  server/src/repositories/cart.respository.ts
  server/src/services/cart.service.ts
Labels: Back

#129 Redirect 컴포넌트 구현
  client/package-lock.json
  client/src/lib/Router.tsx
Labels: enhancement, Front

#132 클라이언트 개발/배포 환경 env 설정파일 분리
  client/.env.sample
  client/.eslintrc
  client/src/lib/api/client.ts
  client/src/lib/api/user/getCurrentUser.ts
  client/webpack.config.js
Labels: Front, chore

#133 회원가입 클라이언트 에러처리 구현, 서버 유저 중복확인 체크 api 기타등등..
  client/src/components/Shared/Input/Input.tsx
  client/src/hooks/useInput.tsx
  client/src/lib/api/login/githubLogin.ts
  client/src/pages/Approval/Approval.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/SignUp/SignUp.tsx
  client/src/utils/constant/validate/validation.ts
  server/package-lock.json
  server/package.json
  server/src/api/middlewares/api.ts
  server/src/api/middlewares/invalid-request.ts
  server/src/api/middlewares/response-format.ts
  server/src/api/routes/index.ts
  server/src/api/routes/user.router.ts
  server/src/controllers/user.controller.ts
  server/src/core/error.ts
  server/src/dtos/user/check.ts
  server/src/types/statusCode.ts
Labels: enhancement, Front, Back

#134 장바구니 api 연동
  client/src/components/MyPage/OrderHistory/OrderHistory.tsx
  client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.tsx
  client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
  client/src/components/ShoppingCart/ShopingCartItem/ShopingCartItem.tsx
  client/src/components/ShoppingCart/ShoppingCartList/ShoppingCart.stories.tsx
  client/src/components/ShoppingCart/ShoppingCartList/ShoppingCartList.tsx
  client/src/dummies/orderHistory.ts
  client/src/hooks/queries/cart/index.tsx
  client/src/lib/api/cart/index.ts
  client/src/pages/ShoppingCart/ShoppingCart.tsx
  client/src/types/index.ts
  server/src/api/routes/cart.router.ts
  server/src/controllers/cart.controller.ts
  server/src/repositories/cart.respository.ts
  server/src/services/cart.service.ts
Labels: Front, Back

#136 로딩 및 에러 컴포넌트 서스펜스 연계하여 작성
  client/package-lock.json
  client/package.json
  client/src/components/MyPage/OrderHistory/OrderHistory.tsx
  client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.stories.tsx
  client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.tsx
  client/src/components/Shared/Error/Error.stories.tsx
  client/src/components/Shared/Error/Error.tsx
  client/src/components/Shared/Error/index.tsx
  client/src/components/Shared/Error/styles.ts
  client/src/components/Shared/Loading/Loading.stories.tsx
  client/src/components/Shared/Loading/Loading.tsx
  client/src/components/Shared/Loading/index.tsx
  client/src/components/Shared/Loading/styles.ts
  client/src/dummies/orderHistory.ts
  client/src/index.tsx
  client/src/layouts/App/App.tsx
  client/src/lib/api/cart/index.ts
  client/src/lib/api/login/githubLogin.ts
Labels: enhancement, Front, refactor

#139 toastify 컴포넌트 작성
  client/package-lock.json
  client/package.json
  client/src/components/Shared/Collapse/Collapse.tsx
  client/src/components/Shared/Modal/Portal/Portal.tsx
  client/src/components/Shared/Toastify/Portal.tsx
  client/src/components/Shared/Toastify/ToastifyContainer.tsx
  client/src/components/Shared/Toastify/index.tsx
  client/src/components/Shared/Toastify/notify.tsx
  client/src/hooks/queries/cart/index.tsx
  client/src/index.html
  client/src/index.tsx
Labels: enhancement, Front, refactor

#143 refactor: purchase table -> order table
  server/src/controllers/order.controller.ts
  server/src/entities/order.entity.ts
  server/src/entities/product.entity.ts
  server/src/entities/user.entity.ts
Labels: Back

#144 로그인 및 회원가입 기능 추가
  client/package-lock.json
  client/src/components/Header/Header.tsx
  client/src/components/Header/Search/Search.tsx
  client/src/components/Header/Sidebar/Sidebar.tsx
  client/src/components/MyPage/MyPageAside/MyPageAside.tsx
  client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.tsx
  client/src/layouts/App/App.tsx
  client/src/lib/api/login/normalLogin.ts
  client/src/lib/api/user/createUser.ts
  client/src/lib/api/user/postEmailCheck.ts
  client/src/pages/Approval/Approval.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Login/styles.ts
  client/src/pages/SelectAuth/SelectAuth.tsx
  client/src/pages/SignUp/SignUp.tsx
  client/src/types/index.ts
  client/src/utils/constant/validate/validation.ts
  server/src/api/middlewares/auth.middleware.ts
  server/src/api/middlewares/checkUser.middleware.ts
  server/src/api/middlewares/oauth.ts
  server/src/api/routes/auth.router.ts
  server/src/api/routes/user.router.ts
  server/src/controllers/auth.controller.ts
  server/src/controllers/user.controller.ts
  server/src/dtos/auth/loginUser.ts
  server/src/dtos/user/createUser.ts
  server/src/repositories/user.repository.ts
  server/src/services/auth.service.ts
  server/src/utils/validate.ts
Labels: enhancement, Front, Back

#149 상품상세 api 데이터 조회를 예시로 API 공통 타입 관련 설정
  client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.tsx
  client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
  client/src/components/ShoppingCart/ShopingCartItem/ShopingCartItem.tsx
  client/src/components/ShoppingCart/ShoppingCartSummary/ShoppingCartSummary.tsx
  client/src/helper/index.ts
  client/src/hooks/queries/product/index.tsx
  client/src/lib/api/product/index.ts
  client/src/pages/Detail/Detail.tsx
  client/src/types/index.ts
  client/src/utils/wonFormat.ts
  server/src/api/middlewares/response-format.ts
  server/src/api/routes/product.router.ts
  server/src/controllers/product.controller.ts
  server/src/services/product.service.ts
Labels: enhancement, Front, Back, refactor

#150 상품상세 API 연동 (part.1 - 정보 및 섬네일 조회)
  client/src/components/ProductDetails/ProductDescription/ProductDescription.tsx
  client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
  client/src/components/ProductDetails/styles.ts
  client/src/components/Shared/Toastify/ToastifyContainer.tsx
  client/src/types/index.ts
  client/src/utils/contentParser.ts
  server/src/controllers/product.controller.ts
  server/src/repositories/product.repository.ts
  server/src/repositories/productImage.repository.ts
  server/src/services/product.service.ts
Labels: enhancement, Front, Back, refactor

#152 헤더 추가 구현
  client/src/components/Header/Header.tsx
  client/src/components/Header/Search/Search.tsx
  client/src/components/Header/Search/SearchItem/SearchItem.tsx
  client/src/components/Header/Search/SearchItem/index.tsx
  client/src/components/Header/Search/SearchItem/style.ts
  client/src/components/Header/Search/styles.ts
  client/src/components/Header/styles.ts
  client/src/components/Shared/Input/Input.tsx
  client/src/components/Shared/Input/style.ts
  client/src/hooks/useRecentSearch.tsx
  client/src/lib/api/product/searchData.ts
  client/src/types/index.ts
  server/src/api/routes/product.router.ts
  server/src/repositories/product.repository.ts
Labels: Front

#153 Feat/main api
  client/src/components/Card/Card.stories.tsx
  client/src/components/Card/Card.tsx
  client/src/components/CardWrapper/CardWrapper.stories.tsx
  client/src/components/ShoppingCart/ShoppingCartSummary/ShoppingCart.stories.tsx
  client/src/hooks/queries/cart/index.tsx
  client/src/hooks/queries/product/index.tsx
  client/src/lib/api/product/index.ts
  client/src/pages/Main/Main.tsx
  client/src/pages/ShoppingCart/ShoppingCart.tsx
  client/src/types/index.ts
  server/src/api/routes/product.router.ts
  server/src/controllers/cart.controller.ts
  server/src/controllers/product.controller.ts
  server/src/entities/order.entity.ts
  server/src/entities/product.entity.ts
  server/src/repositories/order.repository.ts
  server/src/repositories/product.repository.ts
  server/src/services/order.service.ts
  server/src/services/product.service.ts
Labels: Front, Back

#171 [#157] :sparkles refactor: response type 관련 수정
  client/src/components/ProductDetails/ProductDescription/ProductDescription.tsx
  client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
  client/src/hooks/queries/cart/index.tsx
  client/src/hooks/queries/product/index.tsx
  client/src/index.tsx
  client/src/layouts/App/App.tsx
  client/src/lib/api/cart/index.ts
  client/src/lib/api/client.ts
  client/src/lib/api/login/githubLogin.ts
  client/src/lib/api/login/normalLogin.ts
  client/src/lib/api/product/index.ts
  client/src/lib/api/product/searchData.ts
  client/src/lib/api/user/createUser.ts
  client/src/lib/api/user/getCurrentUser.ts
  client/src/lib/api/user/postEmailCheck.ts
  client/src/pages/Main/Main.tsx
  client/src/pages/ShoppingCart/ShoppingCart.tsx
  client/src/types/index.ts
  server/src/api/middlewares/checkUser.middleware.ts
  server/src/api/middlewares/response-format.ts
  server/src/controllers/auth.controller.ts
  server/src/controllers/cart.controller.ts
  server/src/controllers/product.controller.ts
  server/src/controllers/user.controller.ts
Labels: refactor

#174 배송지 api 연동
  client/src/components/Address/Address.tsx
  client/src/components/Shared/Modal/AddressModal/AddressModal.stories.tsx
  client/src/components/Shared/Modal/AddressModal/AddressModal.tsx
  client/src/components/Shared/Modal/AddressModal/index.ts
  client/src/components/Shared/Modal/AddressModal/styles.ts
  client/src/components/Shared/Modal/styles.ts
  client/src/hooks/queries/address/index.tsx
  client/src/lib/api/address/index.ts
  client/src/types/index.ts
  server/src/api/routes/address.router.ts
  server/src/api/routes/index.ts
  server/src/controllers/address.controller.ts
  server/src/entities/address.entity.ts
  server/src/repositories/address.repository.ts
  server/src/services/address.service.ts
  server/src/utils/snakeToCamelObjKey.ts
Labels: Front, Back

#173 로그아웃 구현 및 깃허브 url 충돌 해결 및 유저 가져오는 기능 렌더링시점과 맞추기 feat) 리코일 추가
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/components/Header/Header.tsx
  client/src/components/Header/Sidebar/Sidebar.tsx
  client/src/components/MyPage/MyPageAside/MyPageAside.tsx
  client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.tsx
  client/src/index.tsx
  client/src/layouts/App/App.tsx
  client/src/lib/api/auth/githubLogin.ts
  client/src/lib/api/auth/logout.ts
  client/src/lib/api/auth/normalLogin.ts
  client/src/lib/api/client.ts
  client/src/lib/api/login/githubLogin.ts
  client/src/pages/Approval/Approval.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Mypage/MyPage.tsx
  client/src/pages/SelectAuth/SelectAuth.tsx
  client/src/pages/SignUp/SignUp.tsx
  client/src/recoil/user.ts
  client/src/types/index.ts
  server/src/api/middlewares/auth.middleware.ts
  server/src/api/routes/auth.router.ts
  server/src/controllers/auth.controller.ts
Labels: Front

#176 카테고리 페이지 관련 사항 내용 추가
  client/package.json
  client/src/components/Header/Search/Search.tsx
  client/src/components/Header/Sidebar/Sidebar.tsx
  client/src/components/Shared/Input/Input.tsx
  client/src/hooks/queries/product/index.tsx
  client/src/layouts/App/App.tsx
  client/src/lib/api/product/index.ts
  client/src/lib/api/product/searchData.ts
  client/src/pages/Category/Category.stories.tsx
  client/src/pages/Category/Category.tsx
  client/src/pages/Category/index.tsx
  client/src/pages/Category/styles.ts
  client/src/types/index.ts
  server/src/api/routes/product.router.ts
  server/src/controllers/product.controller.ts
  server/src/entities/mainCategory.entity.ts
  server/src/entities/product.entity.ts
  server/src/entities/subCategory.entity.ts
  server/src/loaders/dataInit.ts
  server/src/repositories/mainCategory.repository.ts
  server/src/repositories/subCategory.repository.ts
  server/src/repositories/user.repository.ts
  server/src/services/product.service.ts
  server/src/utils/combineObjectArray.ts
Labels: Front, Back, hotfix

#177 상품 상세페이지 섬네일 API 연동 및 이미지 확대(zoom) 기능 추가
  client/package-lock.json
  client/src/components/Card/Card.tsx
  client/src/components/ProductDetails/ProductDescription/ProductDescription.tsx
  client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
  client/src/components/ProductDetails/ProductThumbnails/ProductThumbnails.stories.tsx
  client/src/components/ProductDetails/ProductThumbnails/ProductThumbnails.tsx
  client/src/components/ProductDetails/ProductThumbnails/index.tsx
  client/src/components/ProductDetails/ProductThumbnails/zoomLense.ts
  client/src/components/ProductDetails/styles.ts
  client/src/dummies/mockThumbnails.ts
  client/src/hooks/queries/product/index.tsx
  client/src/lib/Router.tsx
  client/src/lib/api/cart/index.ts
  client/src/lib/api/client.ts
  client/src/lib/api/product/index.ts
  client/src/pages/Detail/Detail.stories.tsx
  client/src/pages/Main/Main.tsx
  client/src/types/index.ts
  client/src/utils/thumbnailsParser.ts
  server/src/controllers/product.controller.ts
Labels: enhancement, Front

#178 북마크 api 구현
  server/ormconfig.ts
  server/src/api/middlewares/validation/bookmark/deleteBookmarks.ts
  server/src/api/middlewares/validation/bookmark/getBookmark.ts
  server/src/api/routes/bookmark.router.ts
  server/src/api/routes/index.ts
  server/src/controllers/bookmark.controller.ts
  server/src/entities/bookmark.entity.ts
  server/src/repositories/bookmark.repository.ts
  server/src/services/bookmark.service.ts
Labels: enhancement, Back

#181 주문 페이지 마크업 [주문 1]
  client/src/components/Order/OrderAddress/OrderAddress.tsx
  client/src/components/Order/OrderAddress/index.tsx
  client/src/components/Order/OrderAddress/styles.ts
  client/src/components/Order/OrderCoupon/OrderCoupon.stories.tsx
  client/src/components/Order/OrderCoupon/OrderCoupon.tsx
  client/src/components/Order/OrderCoupon/index.ts
  client/src/components/Order/OrderCoupon/styles.ts
  client/src/components/Order/OrderPayment/OrderPayment.tsx
  client/src/components/Order/OrderPayment/index.tsx
  client/src/components/Order/OrderPayment/styles.ts
  client/src/components/Order/OrderProducts/OrderProducts.stories.tsx
  client/src/components/Order/OrderProducts/OrderProducts.tsx
  client/src/components/Order/OrderProducts/index.tsx
  client/src/components/Order/OrderProducts/styles.ts
  client/src/components/Order/OrderSummary/OrderSummary.tsx
  client/src/components/Order/OrderSummary/index.tsx
  client/src/components/Order/OrderSummary/styles.ts
  client/src/components/Order/styles.ts
  client/src/pages/Order/Order.stories.tsx
  client/src/pages/Order/Order.tsx
  client/src/pages/Order/index.tsx
  client/src/pages/Order/styles.ts
Labels: Front

#183 주문내역 배송지 모달 마크업 [주문 3]
  client/src/assets/svgs/index.ts
  client/src/assets/svgs/left-chevron.svg
  client/src/components/Address/Address.tsx
  client/src/components/Address/AddressForm/AddressForm.tsx
  client/src/components/Address/AddressForm/index.tsx
  client/src/components/Address/AddressForm/styles.ts
  client/src/components/Address/styles.ts
  client/src/components/Shared/Input/Input.tsx
  client/src/components/Shared/Modal/AddressModal/AddressModal.tsx
  client/src/components/Shared/Modal/AddressModal/styles.ts
  client/src/components/ShoppingCart/ShopingCartItem/styles.ts
  client/src/contstants/index.ts
  client/src/layouts/App/App.tsx
  client/src/types/index.ts
Labels: Front

#184 주문결제, 셀렉트 스토리 북 [주문 4]
  client/package-lock.json
  client/src/components/Shared/Select/Select.stories.tsx
  client/src/components/Shared/Select/styles.ts
  client/src/pages/Order/Order.stories.tsx
Labels: Front

#185 찜 메인페이지 및 카드 컴포넌트 연동
  client/src/components/Card/Card.tsx
  client/src/components/Shared/Button/Button.tsx
  client/src/components/Shared/Checkbox/Checkbox.tsx
  client/src/hooks/queries/bookmark/index.tsx
  client/src/lib/api/bookmark/addBookmark.ts
  client/src/lib/api/bookmark/getBookmarkProducts.ts
  client/src/pages/Approval/Approval.tsx
  client/src/pages/Bookmark/Bookmark.tsx
  client/src/pages/Main/Main.tsx
Labels: enhancement, Front

#187 장바구니 페이지 남은 기능 해결 및 텅 컴포넌트 추가, 라벨 버튼 추가
  client/src/assets/index.ts
  client/src/assets/thung.png
  client/src/components/Shared/LabelButton/LabelButton.stories.tsx
  client/src/components/Shared/LabelButton/LabelButton.tsx
  client/src/components/Shared/LabelButton/index.tsx
  client/src/components/Shared/LabelButton/styles.ts
  client/src/components/ShoppingCart/ShopingCartItem/ShopingCartItem.tsx
  client/src/components/ShoppingCart/ShopingCartItem/styles.ts
  client/src/components/ShoppingCart/ShoppingCartList/ShoppingCart.stories.tsx
  client/src/components/ShoppingCart/ShoppingCartList/ShoppingCartList.tsx
  client/src/components/ShoppingCart/ShoppingCartList/styles.ts
  client/src/components/ShoppingCart/ShoppingCartSummary/ShoppingCart.stories.tsx
  client/src/components/ShoppingCart/ShoppingCartSummary/ShoppingCartSummary.tsx
  client/src/components/Thung/Thung.stories.tsx
  client/src/components/Thung/Thung.tsx
  client/src/components/Thung/index.tsx
  client/src/components/Thung/styles.ts
  client/src/pages/Bookmark/Bookmark.tsx
  client/src/pages/ShoppingCart/ShoppingCart.tsx
Labels: enhancement, Front

#186 상품상세 리뷰 작성 API 연동
  client/package-lock.json
  client/package.json
  client/src/components/Address/AddressForm/AddressForm.tsx
  client/src/components/Card/Card.tsx
  client/src/components/Header/Search/SearchItem/SearchItem.tsx
  client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.tsx
  client/src/components/Order/OrderSummary/OrderSummary.tsx
  client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
  client/src/components/ProductDetails/ProductReview/ProductReview.stories.tsx
  client/src/components/ProductDetails/ProductReview/ProductReview.tsx
  client/src/components/ProductDetails/styles.ts
  client/src/components/Shared/Form/Form.tsx
  client/src/components/Shared/Input/FileInput.tsx
  client/src/components/Shared/Input/Input.tsx
  client/src/components/Shared/Input/Textarea.tsx
  client/src/components/Shared/Input/style.ts
  client/src/components/Shared/Modal/ModalLayout/ModalLayout.tsx
  client/src/components/Shared/Modal/ModalLayout/styles.ts
  client/src/components/Shared/Modal/RequestModal.tsx
  client/src/components/Shared/Modal/ReviewModal.tsx
  client/src/components/Shared/Modal/ReviewModal/ReviewImageModal.stories.tsx
  client/src/components/Shared/Modal/ReviewModal/ReviewImageModal.tsx
  client/src/components/Shared/Modal/ReviewModal/ReviewModal.stories.tsx
  client/src/components/Shared/Modal/ReviewModal/ReviewModal.tsx
  client/src/components/Shared/Modal/index.tsx
  client/src/components/Shared/Pagination/Pagination.stories.tsx
  client/src/components/Shared/Pagination/Pagination.tsx
  client/src/components/Shared/Pagination/index.tsx
  client/src/components/Shared/Pagination/styles.ts
  client/src/components/Shared/Rating/RatingGetter.tsx
  client/src/components/Shared/Rating/RatingSetter.stories.tsx
  client/src/components/Shared/Rating/RatingSetter.tsx
  client/src/components/Shared/Rating/styles.ts
  client/src/components/Shared/RatingChart/RatingChart.stories.tsx
  client/src/components/Shared/RatingChart/RatingChart.tsx
  client/src/components/Shared/RatingChart/styles.ts
  client/src/components/Shared/Tab/ProductDetailTab.tsx
  client/src/components/ShoppingCart/ShopingCartItem/ShopingCartItem.tsx
  client/src/components/ShoppingCart/ShoppingCartSummary/ShoppingCartSummary.tsx
  client/src/hooks/queries/product/index.tsx
  client/src/hooks/useFileInput.tsx
  client/src/lib/api/product/index.ts
  client/src/types/index.ts
  client/src/utils/constant/validate/validationReview.ts
  client/src/utils/helper.ts
  client/src/utils/wonFormat.ts
  server/ormconfig.ts
  server/package-lock.json
  server/package.json
  server/src/api/middlewares/s3.middleware.ts
  server/src/api/routes/product.router.ts
  server/src/config/index.ts
  server/src/controllers/product.controller.ts
  server/src/entities/review.entity.ts
  server/src/entities/reviewImage.entity.ts
  server/src/loaders/express.ts
  server/src/repositories/review.repository.ts
  server/src/repositories/reviewImage.repository.ts
  server/src/services/product.service.ts
Labels: enhancement, Front, refactor

#188 Feature/order
  client/package-lock.json
  client/src/components/Address/Address.stories.tsx
  client/src/components/Address/Address.tsx
  client/src/components/Address/AddressForm/AddressForm.tsx
  client/src/components/Address/AddressForm/styles.ts
  client/src/components/Address/styles.ts
  client/src/components/MyPage/OrderHistory/OrderHistory.tsx
  client/src/components/Order/OrderAddress/OrderAddress.tsx
  client/src/components/Order/OrderAddress/styles.ts
  client/src/components/Order/OrderProducts/OrderProducts.tsx
  client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
  client/src/components/Shared/Input/Input.tsx
  client/src/components/Shared/Modal/AddressModal/AddressModal.tsx
  client/src/components/Shared/Modal/AddressModal/styles.ts
  client/src/contstants/index.ts
  client/src/hooks/queries/address/index.tsx
  client/src/hooks/queries/order/index.tsx
  client/src/layouts/App/App.tsx
  client/src/lib/api/address/index.ts
  client/src/lib/api/order/index.ts
  client/src/pages/Mypage/MyPage.tsx
  client/src/pages/Order/Order.tsx
  client/src/pages/Order/styles.ts
  client/src/types/index.ts
  server/src/api/routes/address.router.ts
  server/src/api/routes/index.ts
  server/src/api/routes/order.router.ts
  server/src/controllers/address.controller.ts
  server/src/controllers/order.controller.ts
  server/src/entities/address.entity.ts
  server/src/entities/order.entity.ts
  server/src/entities/orderProduct.entity.ts
  server/src/entities/product.entity.ts
  server/src/repositories/address.repository.ts
  server/src/repositories/order.repository.ts
  server/src/repositories/orderProduct.repository.ts
  server/src/services/address.service.ts
  server/src/services/order.service.ts
  server/src/services/product.service.ts
  server/src/utils/addMonth.ts
Labels: Front, Back

#191 Collapse 컴포넌트 애니메이션 관리 및 기능 리팩토링
  client/src/components/Shared/Collapse/Collapse.tsx
  client/src/components/Shared/Collapse/styles.ts
Labels: Front, refactor

#195 상품상세 - 문의 조회 API 연동 및 페이지네이션 작업
  client/src/components/ProductDetails/ProductRequest/ProductRequest.tsx
  client/src/components/ProductDetails/ProductReview/ProductReview.tsx
  client/src/components/Shared/Collapse/Collapse.tsx
  client/src/hooks/queries/product/index.tsx
  client/src/hooks/usePagination.tsx
  client/src/lib/api/product/index.ts
  client/src/types/index.ts
  server/src/api/routes/product.router.ts
  server/src/controllers/product.controller.ts
  server/src/entities/question.entity.ts
  server/src/repositories/question.repository.ts
  server/src/services/product.service.ts
Labels: enhancement, Front, refactor

#201 주문 결제 페이지 연동
  client/src/components/Address/AddressForm/AddressForm.tsx
  client/src/components/Order/OrderAddress/OrderAddress.tsx
  client/src/components/Order/OrderSummary/OrderSummary.tsx
  client/src/components/Order/OrderSummary/styles.ts
  client/src/components/Shared/Modal/AddressModal/AddressModal.tsx
  client/src/components/ShoppingCart/ShoppingCartSummary/ShoppingCartSummary.stories.tsx
  client/src/components/ShoppingCart/ShoppingCartSummary/ShoppingCartSummary.tsx
  client/src/dummies/shoppingCart.ts
  client/src/hooks/queries/order/index.tsx
  client/src/lib/api/client.ts
  client/src/lib/api/order/index.ts
  client/src/pages/Order/Order.tsx
  client/src/pages/ShoppingCart/ShoppingCart.tsx
  client/src/types/index.ts
  server/src/api/routes/order.router.ts
  server/src/repositories/address.repository.ts
  server/src/repositories/order.repository.ts
  server/src/services/order.service.ts
Labels: Front, Back

#202 장바구니 중복 추가
  server/src/api/routes/cart.router.ts
  server/src/controllers/cart.controller.ts
  server/src/controllers/order.controller.ts
  server/src/repositories/cart.respository.ts
  server/src/services/cart.service.ts
Labels: Back

#204 상품상세 - 문의 작성 API 연동 및 비밀글 설정
  client/src/components/CategorySelector/CategorySelector.stories.tsx
  client/src/components/CategorySelector/CategorySelector.tsx
  client/src/components/ProductDetails/ProductRequest/ProductRequest.tsx
  client/src/components/Shared/Collapse/Collapse.tsx
  client/src/components/Shared/Collapse/styles.ts
  client/src/components/Shared/Input/Input.tsx
  client/src/components/Shared/Input/Textarea.tsx
  client/src/components/Shared/Input/style.ts
  client/src/components/Shared/Modal/RequestModal.tsx
  client/src/components/Shared/Modal/ReviewModal/ReviewModal.tsx
  client/src/components/Shared/Modal/styles.ts
  client/src/hooks/queries/product/index.tsx
  client/src/lib/api/product/index.ts
  client/src/pages/Login/Login.tsx
  client/src/pages/SignUp/SignUp.tsx
  client/src/types/index.ts
  client/src/utils/constant/validate/validationReview.ts
  client/src/utils/validatior.ts
  server/src/api/routes/product.router.ts
  server/src/controllers/product.controller.ts
  server/src/entities/question.entity.ts
  server/src/repositories/question.repository.ts
  server/src/services/product.service.ts
Labels: enhancement, Front, refactor

#205 배송지 vallidation
  client/src/components/Address/AddressForm/AddressForm.tsx
  client/src/components/Address/AddressForm/styles.ts
  client/src/components/Shared/Modal/RequestModal.tsx
  client/src/components/Shared/Modal/ReviewModal/ReviewModal.tsx
  client/src/contstants/index.ts
  client/src/pages/Login/Login.tsx
  client/src/pages/SignUp/SignUp.tsx
  client/src/utils/validator.ts
  server/src/api/routes/address.router.ts
  server/src/dtos/address/index.ts
  server/src/utils/validate.ts
Labels: Front, Back

#207 168 [feat] 카테고리/상품검색 페이지
  client/src/components/CategoryProducts/CategoryProducts.tsx
  client/src/components/SearchProducts/SearchProducts.tsx
  client/src/hooks/queries/product/index.tsx
  client/src/lib/api/product/index.ts
  server/src/controllers/product.controller.ts
  server/src/loaders/express.ts
  server/src/repositories/product.repository.ts
  server/src/services/product.service.ts
Labels: Front, Back, deploy

#211 인피니티 스크롤 구현 및 유저 버그 수정
  client/src/components/Card/Card.tsx
  client/src/components/Skeleton/CardSkeleton/styles.ts
  client/src/hooks/queries/bookmark/index.tsx
  client/src/hooks/useInfiniteScroll.tsx
  client/src/layouts/App/App.tsx
  client/src/lib/api/bookmark/getDetailBookmarkProducts.ts
  client/src/pages/Bookmark/Bookmark.tsx
  client/src/pages/Main/Main.tsx
  server/src/controllers/bookmark.controller.ts
  server/src/repositories/bookmark.repository.ts
  server/src/services/bookmark.service.ts
Labels: Front, Back, refactor

#213 마이페이지 리뷰탭 API 연동
  client/src/assets/svgs/index.ts
  client/src/assets/svgs/more.svg
  client/src/components/MyPage/MyReviews/MyReviews.stories.tsx
  client/src/components/MyPage/MyReviews/MyReviews.tsx
  client/src/components/MyPage/MyReviews/index.tsx
  client/src/components/MyPage/MyReviews/styles.ts
  client/src/components/ProductDetails/ProductRequest/ProductRequest.tsx
  client/src/components/ProductDetails/ProductReview/ProductReview.tsx
  client/src/components/ProductDetails/styles.ts
  client/src/components/Shared/Dropdown/Dropdown.stories.tsx
  client/src/components/Shared/Dropdown/Dropdown.tsx
  client/src/components/Shared/Dropdown/index.tsx
  client/src/components/Shared/Dropdown/styles.ts
  client/src/components/Shared/Modal/AddressModal/AddressModal.stories.tsx
  client/src/components/Shared/Modal/DeleteConfirmModal/DeleteConfirmModal.stories.tsx
  client/src/components/Shared/Modal/DeleteConfirmModal/DeleteConfirmModal.tsx
  client/src/components/Shared/Modal/ModalLayout/ModalLayout.tsx
  client/src/components/Shared/Modal/ModalLayout/styles.ts
  client/src/components/Shared/Modal/RequestModal.stories.tsx
  client/src/components/Shared/Modal/ReviewModal/ReviewImageModal.stories.tsx
  client/src/components/Shared/Modal/ReviewModal/ReviewModal.stories.tsx
  client/src/components/Shared/Modal/index.tsx
  client/src/components/Shared/Modal/styles.ts
  client/src/components/Shared/Tab/TabExample.tsx
  client/src/components/Shared/Tab/TabUI/styles.ts
  client/src/components/Shared/Tab/index.tsx
  client/src/hooks/queries/product/index.tsx
  client/src/hooks/useDropdown.tsx
  client/src/lib/api/client.ts
  client/src/lib/api/product/index.ts
  client/src/pages/Mypage/MyPage.tsx
  client/src/types/index.ts
  client/src/utils/constant/offsetLimit.ts
  server/src/api/routes/product.router.ts
  server/src/controllers/product.controller.ts
  server/src/repositories/question.repository.ts
  server/src/repositories/review.repository.ts
  server/src/services/product.service.ts
Labels: enhancement, Front, Back, refactor

#215 마이페이지 회원정보 변경 관련 api 추가
  server/src/api/middlewares/validation/auth/checkPassword.ts
  server/src/api/middlewares/validation/user/changePassword.ts
  server/src/api/middlewares/validation/user/changeUserNickName.ts
  server/src/api/middlewares/validation/user/check.ts
  server/src/api/middlewares/validation/user/createUser.ts
  server/src/api/routes/auth.router.ts
  server/src/api/routes/user.router.ts
  server/src/controllers/auth.controller.ts
  server/src/controllers/user.controller.ts
  server/src/dtos/user/check.ts
  server/src/dtos/user/createUser.ts
  server/src/entities/question.entity.ts
  server/src/entities/user.entity.ts
  server/src/repositories/user.repository.ts
  server/src/services/auth.service.ts
  server/src/services/user.service.ts
Labels: Back

#216 결제 관련 UI 추가
  client/src/components/MyPage/OrderHistory/OrderHistory.tsx
  client/src/components/MyPage/OrderHistory/styles.ts
  client/src/components/Order/OrderPayment/OrderPayment.tsx
  client/src/components/Order/OrderPayment/styles.ts
  client/src/components/Order/OrderSummary/OrderSummary.tsx
  client/src/components/Order/OrderSummary/styles.ts
  client/src/components/ShoppingCart/ShoppingCartSummary/ShoppingCartSummary.tsx
  client/src/hooks/queries/order/index.tsx
  client/src/layouts/App/App.tsx
  client/src/lib/api/order/index.ts
  client/src/pages/Order/Order.tsx
  client/src/pages/Order/Paid/Paid.stories.tsx
  client/src/pages/Order/Paid/Paid.tsx
  client/src/pages/Order/Paid/index.tsx
  client/src/pages/Order/Paid/styles.ts
  client/src/types/index.ts
  server/src/repositories/order.repository.ts
Labels: Front

#219 메인페이지, 할인율, 카드 디자인 조금 수정
  client/src/components/Card/Card.tsx
  client/src/components/Card/styles.ts
  client/src/components/CardWrapper/styles.ts
  client/src/components/CategoryProducts/CategoryProducts.tsx
  client/src/components/PromotionCard/PromotionCard.tsx
  client/src/components/PromotionCard/index.tsx
  client/src/components/PromotionCard/styles.ts
  client/src/components/SearchProducts/SearchProducts.tsx
  client/src/lib/api/client.ts
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/styles.ts
  client/src/types/index.ts
  server/src/repositories/product.repository.ts
  server/src/services/product.service.ts
Labels: Front, Back

#224 pr 수정 : 메인페이지, 할인율, 카드 디자인 조금 수정
  client/src/components/Card/Card.tsx
  client/src/components/Card/styles.ts
  client/src/components/CardWrapper/styles.ts
  client/src/components/CategoryProducts/CategoryProducts.tsx
  client/src/components/PromotionCard/PromotionCard.tsx
  client/src/components/PromotionCard/index.tsx
  client/src/components/PromotionCard/styles.ts
  client/src/components/SearchProducts/SearchProducts.tsx
  client/src/lib/api/client.ts
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/styles.ts
  client/src/types/index.ts
  client/src/utils/helper.ts
  server/src/repositories/product.repository.ts
  server/src/services/product.service.ts
Labels: bug, Front, Back

#225 마이페이지 문의탭 API 연동
  client/src/components/CategorySelector/CategorySelector.tsx
  client/src/components/MyPage/MyQuestions/MyQuestion.stories.tsx
  client/src/components/MyPage/MyQuestions/MyQuestions.tsx
  client/src/components/MyPage/MyQuestions/index.tsx
  client/src/components/MyPage/MyQuestions/styles.ts
  client/src/components/MyPage/MyReviews/MyReviews.tsx
  client/src/components/ProductDetails/ProductRequest/ProductRequest.tsx
  client/src/components/Shared/Collapse/Collapse.tsx
  client/src/components/Shared/Collapse/styles.ts
  client/src/components/Shared/Dropdown/Dropdown.tsx
  client/src/components/Shared/Dropdown/styles.ts
  client/src/components/Shared/Modal/DeleteConfirmModal/DeleteConfirmModal.tsx
  client/src/components/Shared/Modal/RequestModal/RequestModal.stories.tsx
  client/src/components/Shared/Modal/RequestModal/RequestModal.tsx
  client/src/components/Shared/Modal/RequestModal/RequestUpdateModal.stories.tsx
  client/src/components/Shared/Modal/RequestModal/RequestUpdateModal.tsx
  client/src/components/Shared/Modal/index.tsx
  client/src/hooks/queries/product/index.tsx
  client/src/lib/api/product/index.ts
  client/src/pages/Mypage/MyPage.tsx
  client/src/pages/Notice/Notice.tsx
  client/src/types/index.ts
  client/src/utils/constant/CollapseHeaders.ts
  server/src/api/routes/product.router.ts
  server/src/controllers/product.controller.ts
  server/src/repositories/question.repository.ts
  server/src/services/product.service.ts
Labels: enhancement, Front, Back, refactor

#227 비밀글 열람 조건 변경
  client/src/components/Shared/Collapse/Collapse.tsx
  client/src/types/index.ts
  server/src/entities/user.entity.ts
  server/src/repositories/question.repository.ts
Labels: Front, Back, refactor

#228 ContentParser 파싱 로직 변경
  client/src/components/ProductDetails/ProductDescription/ProductDescription.tsx
  client/src/components/ProductDetails/styles.ts
  client/src/hooks/queries/product/index.tsx
  client/src/utils/contentParser.ts
Labels: Front, refactor

#230 마이 페이지 유저 정보 변경 기능 추가
  client/.storybook/preview.js
  client/src/components/MyPage/ChangeUserInfo/ChangeUserInfo.tsx
  client/src/components/MyPage/ChangeUserInfo/index.tsx
  client/src/components/MyPage/ChangeUserInfo/styles.ts
  client/src/components/MyPage/MyPageAside/MyPageAside.tsx
  client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
  client/src/components/Shared/Input/Input.tsx
  client/src/contstants/index.ts
  client/src/lib/api/auth/passwordCheck.ts
  client/src/lib/api/user/changeNickName.ts
  client/src/lib/api/user/changePassword.ts
  client/src/pages/Mypage/MyPage.tsx
  client/src/types/index.ts
  server/src/api/middlewares/auth.middleware.ts
  server/src/controllers/auth.controller.ts
  server/src/controllers/user.controller.ts
  server/src/entities/user.entity.ts
  server/src/services/auth.service.ts
Labels: enhancement, Front, Back

#229 쿠폰 조회, 생성, 등록, 사용 api
  server/src/api/routes/admin.router.ts
  server/src/api/routes/index.ts
  server/src/api/routes/user.router.ts
  server/src/config/index.ts
  server/src/controllers/admin.controller.ts
  server/src/controllers/user.controller.ts
  server/src/entities/coupon.entity.ts
  server/src/entities/user.entity.ts
  server/src/entities/userCoupon.entity.ts
  server/src/repositories/coupon.repository.ts
  server/src/repositories/userCoupon.repository.ts
  server/src/services/admin.service.ts
  server/src/services/jwt.service.ts
  server/src/services/user.service.ts
Labels: Back

#232 쿠폰 탭 및 쿠폰 컴포넌트 작성
  client/src/components/MyPage/MyCoupon/MyCoupon.stories.tsx
  client/src/components/MyPage/MyCoupon/MyCoupon.tsx
  client/src/components/MyPage/MyCoupon/index.tsx
  client/src/components/MyPage/MyCoupon/styles.ts
  client/src/components/MyPage/MyPageAside/MyPageAside.stories.tsx
  client/src/components/MyPage/MyQuestions/MyQuestion.stories.tsx
  client/src/components/MyPage/MyReviews/MyReviews.stories.tsx
  client/src/components/MyPage/OrderHistory/OrderHistory.stories.tsx
  client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.stories.tsx
  client/src/components/Shared/Coupon/Coupon.stories.tsx
  client/src/components/Shared/Coupon/Coupon.tsx
  client/src/components/Shared/Coupon/index.tsx
  client/src/components/Shared/Coupon/styles.ts
  client/src/pages/Mypage/MyPage.tsx
Labels: enhancement, Front

#233 메인페이지 위주의 스타일 변경
  client/src/components/Card/Card.tsx
  client/src/components/Card/styles.ts
  client/src/components/CardWrapper/CardWrapper.stories.tsx
  client/src/components/CardWrapper/CardWrapper.tsx
  client/src/components/CardWrapper/styles.ts
  client/src/components/CategoryProducts/CategoryProducts.tsx
  client/src/components/Footer/styles.ts
  client/src/components/Header/Search/Search.tsx
  client/src/components/Header/Search/SearchItem/SearchItem.tsx
  client/src/components/Header/Search/SearchItem/style.ts
  client/src/components/Header/Search/styles.ts
  client/src/components/PromotionCard/PromotionCard.tsx
  client/src/components/PromotionCard/styles.ts
  client/src/components/SearchProducts/SearchProducts.tsx
  client/src/components/Shared/Input/Input.tsx
  client/src/components/Skeleton/LoadingCards/LoadingCards.tsx
  client/src/lib/api/product/index.ts
  client/src/pages/Approval/styles.ts
  client/src/pages/Bookmark/Bookmark.tsx
  client/src/pages/Bookmark/style.ts
  client/src/pages/Category/styles.ts
  client/src/pages/Detail/styles.ts
  client/src/pages/Login/styles.ts
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/styles.ts
  client/src/pages/Mypage/styles.ts
  client/src/pages/Notice/styles.ts
  client/src/pages/Order/styles.ts
  client/src/pages/Search/styles.ts
  client/src/pages/ShoppingCart/styles.ts
  client/src/pages/SignUp/styles.ts
  client/src/styles/globalStyle.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/src/types/index.ts
  client/src/utils/constant/offsetLimit.ts
  server/src/controllers/product.controller.ts
Labels: Front

#238 dto -> valdation 이사, api jwt 적용
  client/src/components/Card/Card.tsx
  client/src/pages/Bookmark/Bookmark.tsx
  server/src/api/middlewares/validation/address/index.ts
  server/src/api/middlewares/validation/auth/loginUser.ts
  server/src/api/routes/address.router.ts
  server/src/api/routes/auth.router.ts
  server/src/api/routes/cart.router.ts
  server/src/api/routes/order.router.ts
  server/src/api/routes/user.router.ts
  server/src/controllers/address.controller.ts
  server/src/controllers/cart.controller.ts
  server/src/controllers/order.controller.ts
  server/src/controllers/user.controller.ts
  server/src/dtos/auth/loginUser.ts
Labels: Back

#239 Footer 구조 변경 및 페이지 연결
  client/src/components/Footer/Footer.tsx
  client/src/components/Footer/styles.ts
  client/src/layouts/App/App.tsx
  client/src/pages/Terms/TermsOfPrivacy.stories.tsx
  client/src/pages/Terms/TermsOfPrivacy.tsx
  client/src/pages/Terms/TermsOfUes.stories.tsx
  client/src/pages/Terms/TermsOfUse.tsx
  client/src/pages/Terms/index.tsx
  client/src/pages/Terms/styles.ts
  client/src/pages/Vendor/Vendor.stories.tsx
  client/src/pages/Vendor/Vendor.tsx
  client/src/pages/Vendor/index.tsx
  client/src/pages/Vendor/styles.ts
  client/src/utils/constant/terms.ts
Labels: enhancement, Front, refactor

#315 테마 로컬스토리지 저장
  client/src/components/Footer/styles.ts
  client/src/hooks/useGlobalTheme.tsx
  client/src/hooks/useRecentSearch.tsx
  client/src/layouts/App/App.tsx
  client/src/lib/api/client.ts
  client/src/styles/globalStyle.ts
  client/src/styles/styled.d.ts
  client/src/utils/constant/common.ts
Labels: Front

#322 🐛 bug: 다크모드 변경 안되는 것 수정
  client/src/hooks/useGlobalTheme.tsx
Labels: bug, hotfix

#328 미션 기능 추가
  client/src/assets/svgs/index.ts
  client/src/assets/svgs/target.svg
  client/src/components/Card/Card.tsx
  client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
  client/src/components/Shared/Modal/MissionModal/MissionModal.tsx
  client/src/components/Shared/Modal/MissionModal/ProgressBar/ProgressBar.tsx
  client/src/components/Shared/Modal/MissionModal/ProgressBar/index.tsx
  client/src/components/Shared/Modal/MissionModal/ProgressBar/styles.ts
  client/src/components/Shared/Modal/MissionModal/index.ts
  client/src/components/Shared/Modal/MissionModal/styles.ts
  client/src/components/ThemeChanger/ThemeChanger.tsx
  client/src/components/ThemeChanger/styles.ts
  client/src/hooks/useMission.tsx
  client/src/layouts/App/App.tsx
  client/src/pages/Login/Login.tsx
  client/src/types/index.ts
Labels: enhancement, Front

#326 마이페이지 사이드바 반응형 및 다크모드 디자인
  README.md
  client/src/assets/svgs/contract.svg
  client/src/assets/svgs/coupon.svg
  client/src/assets/svgs/history.svg
  client/src/assets/svgs/index.ts
  client/src/assets/svgs/logout.svg
  client/src/assets/svgs/rating.svg
  client/src/components/MyPage/MyCoupon/MyCoupon.tsx
  client/src/components/MyPage/MyCoupon/styles.ts
  client/src/components/MyPage/MyPageAside/MyPageAside.tsx
  client/src/components/MyPage/MyPageAside/styles.ts
  client/src/components/MyPage/MyQuestions/MyQuestions.tsx
  client/src/components/MyPage/MyQuestions/styles.ts
  client/src/components/MyPage/MyReviews/MyReviews.tsx
  client/src/components/MyPage/MyReviews/styles.ts
  client/src/components/ProductDetails/styles.ts
  client/src/components/Shared/Coupon/styles.ts
  client/src/components/Shared/Dropdown/styles.ts
  client/src/components/Shared/Modal/ModalLayout/styles.ts
  client/src/components/Shared/Modal/styles.ts
  client/src/components/Shared/Pagination/styles.ts
  client/src/contstants/index.ts
  client/src/pages/Mypage/MyPage.tsx
  client/src/pages/Mypage/styles.ts
  client/src/pages/Order/Paid/styles.ts
  client/src/styles/globalStyle.ts
  client/src/styles/styled.d.ts
Labels: enhancement, Front, refactor, design

#324 배민팡 favicon 및 제목 변경
  client/src/assets/favicon.ico
  client/src/index.html
  client/webpack.config.js
Labels: design

#327 주문내역 반응형
  client/src/components/MyPage/OrderHistory/OrderHistory.tsx
  client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.tsx
  client/src/components/MyPage/OrderHistory/OrderItemList/styles.ts
  client/src/components/MyPage/OrderHistory/styles.ts
  client/src/components/Shared/Pagination/styles.ts
  client/src/components/Thung/styles.ts
  client/src/contstants/index.ts
  client/src/pages/Mypage/styles.ts
Labels: Front, design

#330 결제 쿠폰 반응형, 배송 버그 수정
  client/src/components/Order/OrderCoupon/OrderCoupon.tsx
  client/src/components/Order/OrderCoupon/styles.ts
  client/src/components/Shared/Coupon/styles.ts
  client/src/components/Shared/Modal/CouponModal/CouponModal.stories.tsx
  client/src/components/Shared/Modal/CouponModal/CouponModal.tsx
  client/src/components/Shared/Modal/CouponModal/index.ts
  client/src/components/Shared/Modal/CouponModal/styles.ts
  client/src/pages/Order/Paid/Paid.tsx
Labels: Front, design

#331 전체적인 페이지 디자인 점검
  client/src/components/Card/Card.stories.tsx
  client/src/components/Card/Card.tsx
  client/src/components/Card/styles.ts
  client/src/components/CardWrapper/styles.ts
  client/src/components/CategoryProducts/styles.ts
  client/src/components/Footer/styles.ts
  client/src/components/Header/Sidebar/styles.ts
  client/src/components/Header/styles.ts
  client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
  client/src/components/ProductDetails/styles.ts
  client/src/components/Shared/Modal/MissionModal/MissionModal.tsx
  client/src/components/Shared/Modal/MissionModal/ProgressBar/ProgressBar.tsx
  client/src/components/Shared/Modal/MissionModal/ProgressBar/styles.ts
  client/src/components/Shared/Modal/MissionModal/styles.ts
  client/src/components/Shared/RatingChart/RatingChart.tsx
  client/src/components/Shared/RatingChart/styles.ts
  client/src/components/Shared/Toastify/notify.tsx
  client/src/components/Shared/Toastify/styles.ts
  client/src/components/ThemeChanger/styles.ts
  client/src/layouts/App/App.tsx
  client/src/pages/Bookmark/Bookmark.tsx
  client/src/pages/Bookmark/style.ts
  client/src/pages/Category/Category.tsx
  client/src/pages/Category/styles.ts
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/styles.ts
  client/src/pages/Mypage/MyPage.tsx
  client/src/pages/Mypage/styles.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  server/src/services/product.service.ts
Labels: bug, enhancement, Front, refactor, design

#332 289 [design] 공지사항, 이용약관. 개인정보, 판매처안내 및 푸터 페이지 반응형 및 다크모드
  client/src/components/Header/Search/SearchItem/style.ts
  client/src/components/Header/Search/styles.ts
  client/src/components/Header/Sidebar/styles.ts
  client/src/components/Header/styles.ts
  client/src/components/Shared/Collapse/Collapse.tsx
  client/src/components/Shared/Collapse/styles.ts
  client/src/pages/Notice/Notice.tsx
  client/src/pages/Notice/styles.ts
  client/src/pages/Terms/styles.ts
  client/src/pages/Vendor/Vendor.tsx
  client/src/pages/Vendor/styles.ts
Labels: Front, refactor, design

#334 useMission 개선
  client/src/components/Card/Card.tsx
  client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
  client/src/components/Shared/Modal/MissionModal/MissionModal.tsx
  client/src/contstants/index.ts
  client/src/hooks/useMission.tsx
  client/src/layouts/App/App.tsx
Labels: Front

#337 전체적인 페이지 디자인 점검(2)
  client/src/components/Card/styles.ts
  client/src/components/Header/Header.tsx
  client/src/components/Header/Search/SearchItem/style.ts
  client/src/components/Header/Search/styles.ts
  client/src/components/Header/styles.ts
  client/src/components/MyPage/ChangeUserInfo/ChangeUserInfo.tsx
  client/src/components/MyPage/ChangeUserInfo/styles.ts
  client/src/components/MyPage/MyReviews/styles.ts
  client/src/components/Order/OrderCoupon/styles.ts
  client/src/components/Order/OrderPayment/styles.ts
  client/src/components/Shared/Modal/CouponModal/CouponModal.tsx
  client/src/components/Shared/Modal/CouponModal/styles.ts
  client/src/components/Shared/Modal/DeliveryModal/styles.ts
  client/src/components/Shared/Modal/MissionModal/MissionModal.tsx
  client/src/components/Shared/Modal/MissionModal/ProgressBar/ProgressBar.tsx
  client/src/components/Shared/Modal/MissionModal/ProgressBar/styles.ts
  client/src/components/Shared/Modal/MissionModal/styles.ts
  client/src/components/Shared/Modal/ShoppingCartModal/styles.ts
  client/src/components/Shared/Spinner/Spinner.tsx
  client/src/components/Shared/Spinner/styles.ts
  client/src/components/ShoppingCart/ShoppingCartList/styles.ts
  client/src/pages/Approval/Approval.tsx
  client/src/pages/Approval/styles.ts
  client/src/pages/Login/Login.tsx
  client/src/pages/Login/styles.ts
  client/src/pages/Mypage/styles.ts
  client/src/pages/Order/Paid/Paid.tsx
  client/src/pages/Order/Paid/styles.ts
  client/src/pages/Order/styles.ts
  client/src/pages/Search/Search.tsx
  client/src/pages/Search/styles.ts
  client/src/pages/SelectAuth/SelectAuth.tsx
  client/src/pages/SelectAuth/styles.ts
  client/src/pages/ShoppingCart/ShoppingCart.tsx
  client/src/pages/ShoppingCart/styles.ts
  client/src/pages/SignUp/SignUp.tsx
  client/src/pages/SignUp/styles.ts
  client/src/styles/global.scss
Labels: enhancement, Front, refactor, design

#339 전체적인 페이지 디자인 점검(완)
  client/src/components/MyPage/MyQuestions/MyQuestions.tsx
  client/src/components/MyPage/MyReviews/MyReviews.tsx
  client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
  client/src/components/Shared/Coupon/Coupon.tsx
  client/src/components/Shared/Coupon/styles.ts
  client/src/components/Shared/Modal/CouponModal/CouponModal.tsx
  client/src/components/Shared/Modal/CouponModal/styles.ts
  client/src/components/Skeleton/ProductSkeleton/InfoSkeleton.tsx
Labels: Front, refactor, design

#341 미리셔련 추루가라
  client/src/assets/svgs/delivery.svg
  client/src/assets/svgs/filter.svg
  client/src/assets/svgs/index.ts
  client/src/assets/svgs/location.svg
  client/src/assets/svgs/money.svg
  client/src/components/Card/Card.tsx
  client/src/components/MyPage/OrderHistory/OrderHistory.tsx
  client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
  client/src/components/Shared/Modal/MissionModal/MissionModal.tsx
  client/src/components/Shared/Modal/MissionModal/styles.ts
  client/src/contstants/index.ts
  client/src/hooks/queries/address/index.tsx
  client/src/pages/Order/Paid/Paid.tsx
  client/src/types/index.ts
Labels: Front

#342 검색 & 카테고리 이동 미션
  client/src/components/Header/Search/Search.tsx
  client/src/components/Header/Sidebar/Sidebar.tsx
  client/src/components/Shared/Modal/MissionModal/MissionModal.tsx
  client/src/contstants/index.ts
  client/src/types/index.ts
Labels: Front

#344 리드미 업데이트
  README.md
Labels: documentation

#345 Mission Complete
  client/src/assets/svgs/file.svg
  client/src/assets/svgs/index.ts
  client/src/assets/svgs/padlock.svg
  client/src/assets/svgs/tap.svg
  client/src/components/Header/styles.ts
  client/src/components/ProductDetails/ProductDescription/ProductDescription.tsx
  client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
  client/src/components/ProductDetails/ProductReview/ProductReview.tsx
  client/src/components/Shared/Modal/MissionModal/MissionModal.tsx
  client/src/components/Shared/Modal/MissionModal/ProgressBar/styles.ts
  client/src/components/Shared/Modal/MissionModal/styles.ts
  client/src/components/Shared/Modal/ModalLayout/styles.ts
  client/src/components/Shared/Modal/RequestModal/RequestModal.tsx
  client/src/components/Shared/Modal/RequestModal/RequestUpdateModal.tsx
  client/src/components/Shared/Modal/ReviewModal/ReviewModal.tsx
  client/src/components/Shared/Modal/ReviewModal/ReviewUpdateModal.tsx
  client/src/contstants/index.ts
  client/src/hooks/useNumberInput.tsx
  client/src/layouts/App/App.tsx
  client/src/pages/Category/Category.tsx
  client/src/pages/Notice/Notice.tsx
  client/src/types/index.ts
Labels: enhancement, Front

#346 미션 완료 쿠폰
  client/src/components/Shared/Modal/MissionModal/MissionModal.tsx
  client/src/components/Shared/Modal/MissionModal/styles.ts
  client/src/hooks/queries/coupon/index.ts
  client/src/lib/api/user/index.ts
  client/src/pages/Main/Main.tsx
  server/src/api/routes/user.router.ts
  server/src/controllers/admin.controller.ts
  server/src/controllers/user.controller.ts
  server/src/entities/issuedCoupon.entity.ts
  server/src/entities/userCoupon.entity.ts
  server/src/repositories/issuedCoupon.repository.ts
  server/src/repositories/userCoupon.repository.ts
  server/src/services/admin.service.ts
  server/src/services/user.service.ts
Labels: Front, Back

#348 발급된 쿠폰이 케쉬되지 않도록 합니다.
  client/src/hooks/queries/coupon/index.ts
Labels: bug

#350 최종점검 얍!
  client/src/components/Card/styles.ts
  client/src/components/Header/Sidebar/styles.ts
  client/src/components/Shared/Modal/MissionModal/MissionModal.tsx
  client/src/components/Shared/Modal/MissionModal/styles.ts
  client/src/layouts/App/App.tsx
Labels: enhancement, Front, design
